Remove instances of the type membership overload
Quantco/spox pull request #44
Opened 2023-03-03 13:26 UTC by JakubBachurskiQC

Previously, we exposed `Type.__le__` for checking if a type is essentially a subtype of another type. This was used in some places internally, and was partially documented. This PR moves `Type.__le__` to `Type._subtype(Type) -> bool`, which is a possible (though unlikely) **breaking change**.

2023-03-09 08:44 UTC, cbourjau approved these changes

2023-03-09 09:02 UTC, cbourjau requested changes
Actually, I am pretty sure that this is not breaking anything, but let's do this by the book with a proper deprecation for at least one version.

2023-03-09 17:05 UTC, cbourjau commented
Yes, no need to put it into its own release. Thanks :)

2023-03-14 18:41 UTC, JakubBachurskiQC commented
@cbourjau Sorry for the delay - this PR now raises a deprecation warning on usage with a dedicated test, set for `0.6.2`. `0.7.0` can remove the `__le__` method and respective test.

2023-03-17 16:52 UTC, cbourjau approved these changes

2023-03-17 16:53 UTC, merged