Raise a warning when a deprecated operator is used
Quantco/spox pull request #62
Opened 2023-03-20 18:24 UTC by JakubBachurskiQC

This is a first step at #58. Warnings are raised when deprecated operators are used. See the issue for a description.

2023-03-21 17:55 UTC, cbourjau requested changes
I don't think it is spox responsibility to remove the constructors as long as there is an operator of that name and version in the standard. The warning is very nice though. What was your motivation to remove the constructor functions?

2023-03-21 17:55 UTC, cbourjau commented on CHANGELOG.rst
> +- Constructors for deprecated ONNX operators (currently ``Scatter`` and ``Upsample``) now raise a warning when they are called. They will be removed entirely in ``0.7.0``.
I don't think we should remove operators from spox which are still in the standard. The warning is super nice for the user though!

2023-03-21 17:59 UTC, JakubBachurskiQC commented
No operators were ever removed as far as I'm aware. They only get marked as deprecated from some version onwards and my understanding is that means they are effectively removed. For instance Scatter was renamed in this way to ScatterElements to mirror GatherElements. Definitely feels like we shouldn't just offer them up normally if at some point ONNX (and especially other tools) might start throwing errors about it.

2023-03-21 19:08 UTC, JakubBachurskiQC commented
I think this is conclusive to show we shouldn't produce deprecated operators - https://github.com/onnx/sigs/issues/18

2023-03-21 19:28 UTC, JakubBachurskiQC commented
Attempting to check a model with a deprecated operator always results in a `ValidationError`, but because in some of the technicalities in how Spox checks individual nodes this only raises when the graph is actually built:

```py
def test_deprecated_raises(op):
    (x,) = arguments(x=Tensor(float, (None,)))
    s = op.const(numpy.array([2.0], numpy.float32))
    with pytest.warns(DeprecationWarning):
        y = op.upsample(x, s)  # Uses the new warning
    graph = results(y=y).with_arguments(x)
    with pytest.raises(Exception):
        graph.to_onnx_model()  # Will always fail since check_model is called
```

2023-03-23 06:53 UTC, cbourjau commented
Fair enough. Could you add a sentence to the warning that graphs with deprecated operators fail to build today, please?

2023-03-23 06:53 UTC, cbourjau approved these changes

2023-03-23 11:30 UTC, JakubBachurskiQC commented on tools/templates/construct.jinja2
> +    "Deprecated constructors will be removed in Spox 0.7.0.",
```suggestion
    "Building will raise an error. "
    "Deprecated constructors will be removed in Spox 0.7.0.",
```

2023-03-23 11:30 UTC, JakubBachurskiQC commented on src/spox/opset/ai/onnx/v17.py
> +        "Deprecated constructors will be removed in Spox 0.7.0.",
```suggestion
    "Building will raise an error. "
    "Deprecated constructors will be removed in Spox 0.7.0.",
```

2023-03-23 12:06 UTC, merged